package app

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"syscall"
	"time"
)

func directive(proto string) (string, error) {
	switch proto {
	case "udp":
		return "server", nil
	case "tcp":
		return "server-tcp", nil
	case "dot":
		return "server-tls", nil
	case "doh":
		return "server-https", nil
	case "doq":
		return "server-quic", nil
	case "doh3":
		return "server-h3", nil
	default:
		return "", fmt.Errorf("unsupported proto %q", proto)
	}
}

func Render(cfg Config, s State, rules RulesFile) error {
	if err := os.MkdirAll(cfg.RuntimeDir, 0755); err != nil {
		return err
	}
	rd := filepath.Join(cfg.RuntimeDir, "rules")
	if err := os.MkdirAll(rd, 0755); err != nil {
		return err
	}
	ids := make([]string, 0, len(rules.Rules))
	for id := range rules.Rules {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		if err := os.WriteFile(filepath.Join(rd, id+".txt"), []byte(strings.Join(rules.Rules[id], "\n")+"\n"), 0644); err != nil {
			return err
		}
	}
	var up strings.Builder
	up.WriteString("# generated by smartunlock\n")
	if cfg.Primary != "" {
		d, e := directive(cfg.PrimaryProto)
		if e != nil {
			return e
		}
		fmt.Fprintf(&up, "%s %s -group unlock_primary -exclude-default-group\n", d, cfg.Primary)
	}
	if cfg.Backup != "" {
		d, e := directive(cfg.BackupProto)
		if e != nil {
			return e
		}
		fmt.Fprintf(&up, "%s %s -group unlock_backup -exclude-default-group\n", d, cfg.Backup)
	}
	if err := os.WriteFile(filepath.Join(cfg.RuntimeDir, "upstreams.conf"), []byte(up.String()), 0644); err != nil {
		return err
	}
	var pf strings.Builder
	pf.WriteString("# generated by smartunlock\n")
	for _, p := range Platforms {
		mode := s.Routes[p.ID]
		if mode == "" {
			mode = "primary"
		}
		if mode == "off" || mode == "native" {
			continue
		}
		group := mode
		if group == "primary" && !s.PrimaryHealthy && s.BackupHealthy && cfg.Backup != "" {
			group = "backup"
		}
		if group == "backup" && !s.BackupHealthy && s.PrimaryHealthy && cfg.Primary != "" {
			group = "primary"
		}
		if group == "backup" && cfg.Backup == "" {
			group = "primary"
		}
		if group == "primary" && cfg.Primary == "" {
			continue
		}
		if group == "backup" && cfg.Backup == "" {
			continue
		}
		if group != "primary" && group != "backup" {
			continue
		}
		if _, ok := rules.Rules[p.ID]; !ok {
			continue
		}
		name := "su_" + strings.ReplaceAll(p.ID, "-", "_")
		fmt.Fprintf(&pf, "domain-set -name %s -file %s\n", name, filepath.Join(rd, p.ID+".txt"))
		fmt.Fprintf(&pf, "domain-rules /domain-set:%s/ -nameserver unlock_%s -speed-check-mode none -response-mode fastest-response\n", name, group)
	}
	if err := os.WriteFile(filepath.Join(cfg.RuntimeDir, "platforms.conf"), []byte(pf.String()), 0644); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(cfg.SmartDNSConf), 0755); err != nil {
		return err
	}
	var healthBinds strings.Builder
	if cfg.Primary != "" {
		fmt.Fprintf(&healthBinds, "bind %s -group unlock_primary -no-cache -no-speed-check\n", cfg.HealthPrimaryAddr)
	}
	if cfg.Backup != "" {
		fmt.Fprintf(&healthBinds, "bind %s -group unlock_backup -no-cache -no-speed-check\n", cfg.HealthBackupAddr)
	}
	conf := fmt.Sprintf(`# Managed by smartunlock
server-name smartunlock
bind 127.0.0.1:53
bind [::1]:53
%s
cache-size 32768
cache-persist yes
cache-file /var/cache/smartdns/smartdns.cache
prefetch-domain yes
serve-expired yes
speed-check-mode tcp:443
response-mode first-ping
log-level notice
log-file /var/log/smartdns/smartdns.log
log-size 4M
log-num 3
server-https https://cloudflare-dns.com/dns-query -host-ip 1.1.1.1
server-https https://dns.google/dns-query -host-ip 8.8.8.8
conf-file %s
conf-file %s
`, healthBinds.String(), filepath.Join(cfg.RuntimeDir, "upstreams.conf"), filepath.Join(cfg.RuntimeDir, "platforms.conf"))
	return os.WriteFile(cfg.SmartDNSConf, []byte(conf), 0644)
}

type SmartDNSProcess struct {
	mu  sync.Mutex
	cmd *exec.Cmd
	cfg Config
}

func NewSmartDNSProcess(cfg Config) *SmartDNSProcess { return &SmartDNSProcess{cfg: cfg} }
func (p *SmartDNSProcess) SetConfig(cfg Config) {
	p.mu.Lock()
	p.cfg = cfg
	p.mu.Unlock()
}
func (p *SmartDNSProcess) Start() error {
	p.mu.Lock()
	defer p.mu.Unlock()
	if p.cmd != nil && p.cmd.Process != nil {
		return nil
	}
	cmd := exec.Command(p.cfg.SmartDNSBin, "-f", "-x", "-c", p.cfg.SmartDNSConf)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		return err
	}
	p.cmd = cmd
	go func() {
		_ = cmd.Wait()
		p.mu.Lock()
		if p.cmd == cmd {
			p.cmd = nil
		}
		p.mu.Unlock()
	}()
	time.Sleep(500 * time.Millisecond)
	return nil
}
func (p *SmartDNSProcess) Restart() error {
	p.mu.Lock()
	if p.cmd != nil && p.cmd.Process != nil {
		_ = p.cmd.Process.Signal(syscall.SIGTERM)
		for i := 0; i < 20; i++ {
			if p.cmd.ProcessState != nil {
				break
			}
			time.Sleep(100 * time.Millisecond)
		}
	}
	p.cmd = nil
	p.mu.Unlock()
	return p.Start()
}
func (p *SmartDNSProcess) Stop() {
	p.mu.Lock()
	defer p.mu.Unlock()
	if p.cmd != nil && p.cmd.Process != nil {
		_ = p.cmd.Process.Signal(syscall.SIGTERM)
	}
}

func DNSQueryOK() bool {
	cmd := exec.Command("getent", "ahostsv4", "github.com")
	return cmd.Run() == nil
}

func ReadFirstNameserver(path string) string {
	f, e := os.Open(path)
	if e != nil {
		return ""
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fs := strings.Fields(sc.Text())
		if len(fs) >= 2 && fs[0] == "nameserver" {
			return fs[1]
		}
	}
	return ""
}
