package app

import (
	"bufio"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"syscall"
	"time"
)

func directive(proto string) (string, error) {
	switch proto {
	case "udp":
		return "server", nil
	case "tcp":
		return "server-tcp", nil
	case "dot":
		return "server-tls", nil
	case "doh":
		return "server-https", nil
	case "doq":
		return "server-quic", nil
	case "doh3":
		return "server-h3", nil
	default:
		return "", fmt.Errorf("unsupported proto %q", proto)
	}
}

func ipv6LoopbackAvailable() bool {
	ifaces, err := net.Interfaces()
	if err != nil { return false }
	for _, iface := range ifaces {
		addrs, err := iface.Addrs()
		if err != nil { continue }
		for _, addr := range addrs {
			var ip net.IP
			switch v := addr.(type) {
			case *net.IPNet:
				ip = v.IP
			case *net.IPAddr:
				ip = v.IP
			}
			if ip != nil && ip.To4() == nil && ip.Equal(net.IPv6loopback) { return true }
		}
	}
	return false
}

func Render(cfg Config, s State, rules RulesFile) error {
	if err := os.MkdirAll(cfg.RuntimeDir, 0755); err != nil { return err }
	rd := filepath.Join(cfg.RuntimeDir, "rules")
	if err := os.MkdirAll(rd, 0755); err != nil { return err }
	ids := make([]string, 0, len(rules.Rules))
	for id := range rules.Rules { ids = append(ids, id) }
	sort.Strings(ids)
	for _, id := range ids {
		if err := os.WriteFile(filepath.Join(rd, id+".txt"), []byte(strings.Join(rules.Rules[id], "\n")+"\n"), 0644); err != nil { return err }
	}
	var up strings.Builder
	up.WriteString("# generated by smartunlock\n")
	if cfg.Primary != "" {
		d, e := directive(cfg.PrimaryProto); if e != nil { return e }
		fmt.Fprintf(&up, "%s %s -group unlock_primary -exclude-default-group\n", d, cfg.Primary)
	}
	if cfg.Backup != "" {
		d, e := directive(cfg.BackupProto); if e != nil { return e }
		fmt.Fprintf(&up, "%s %s -group unlock_backup -exclude-default-group\n", d, cfg.Backup)
	}
	if err := os.WriteFile(filepath.Join(cfg.RuntimeDir, "upstreams.conf"), []byte(up.String()), 0644); err != nil { return err }

	var pf strings.Builder
	pf.WriteString("# generated by smartunlock\n")
	for _, p := range Platforms {
		mode := s.Routes[p.ID]; if mode == "" { mode = "primary" }
		if mode == "off" || mode == "native" { continue }
		group := mode
		manual := s.RouteMode(p.ID) == "manual"

		// Health failover is deliberately non-destructive: State.Routes keeps the
		// automatically selected route. If the desired line is down, use the other healthy
		// unlock line. If neither configured unlock line is healthy, omit the
		// platform rule entirely so SmartDNS's default public resolvers preserve
		// basic reachability. Manual routes are pinned exactly as requested and
		// never fail over behind the user's back.
		if !manual && group == "primary" {
			if cfg.Primary == "" || !s.PrimaryHealthy {
				if cfg.Backup != "" && s.BackupHealthy {
					group = "backup"
				} else {
					continue
				}
			}
		} else if !manual && group == "backup" {
			if cfg.Backup == "" || !s.BackupHealthy {
				if cfg.Primary != "" && s.PrimaryHealthy {
					group = "primary"
				} else {
					continue
				}
			}
		}
		if group != "primary" && group != "backup" { continue }
		if _, ok := rules.Rules[p.ID]; !ok { continue }
		name := "su_" + strings.ReplaceAll(p.ID, "-", "_")
		fmt.Fprintf(&pf, "domain-set -name %s -file %s\n", name, filepath.Join(rd, p.ID+".txt"))
		// Unlock answers can change immediately when a route fails over. Do not
		// let SmartDNS memory/persistent/expired cache keep serving the old
		// primary answer after switching to backup (or back again).
		fmt.Fprintf(&pf, "domain-rules /domain-set:%s/ -nameserver unlock_%s -speed-check-mode none -response-mode fastest-response -no-cache -no-serve-expired\n", name, group)
	}
	if err := os.WriteFile(filepath.Join(cfg.RuntimeDir, "platforms.conf"), []byte(pf.String()), 0644); err != nil { return err }
	if err := os.MkdirAll(filepath.Dir(cfg.SmartDNSConf), 0755); err != nil { return err }

	var mainBinds strings.Builder
	mainBinds.WriteString("bind 127.0.0.1:53\n")
	// Some VPS kernels disable IPv6 completely, which removes ::1 from lo.
	// SmartDNS treats an unavailable [::1]:53 bind as fatal, so only emit the
	// IPv6 listener when the kernel actually exposes the IPv6 loopback address.
	if ipv6LoopbackAvailable() { mainBinds.WriteString("bind [::1]:53\n") }

	var healthBinds strings.Builder
	if cfg.Primary != "" { fmt.Fprintf(&healthBinds, "bind %s -group unlock_primary -no-cache -no-speed-check\n", cfg.HealthPrimaryAddr) }
	if cfg.Backup != "" { fmt.Fprintf(&healthBinds, "bind %s -group unlock_backup -no-cache -no-speed-check\n", cfg.HealthBackupAddr) }
	conf := fmt.Sprintf(`# Managed by smartunlock
server-name smartunlock
%s%s
cache-size 32768
cache-persist yes
cache-file /var/cache/smartdns/smartdns.cache
prefetch-domain yes
serve-expired yes
speed-check-mode tcp:443
response-mode first-ping
log-level notice
log-file /var/log/smartdns/smartdns.log
log-size 4M
log-num 3
server-https https://cloudflare-dns.com/dns-query -host-ip 1.1.1.1
server-https https://dns.google/dns-query -host-ip 8.8.8.8
conf-file %s
conf-file %s
`, mainBinds.String(), healthBinds.String(), filepath.Join(cfg.RuntimeDir, "upstreams.conf"), filepath.Join(cfg.RuntimeDir, "platforms.conf"))
	return os.WriteFile(cfg.SmartDNSConf, []byte(conf), 0644)
}

type SmartDNSProcess struct {
	mu  sync.Mutex
	cmd *exec.Cmd
	done chan struct{}
	cfg Config
}

func NewSmartDNSProcess(cfg Config) *SmartDNSProcess { return &SmartDNSProcess{cfg: cfg} }
func (p *SmartDNSProcess) SetConfig(cfg Config) { p.mu.Lock(); p.cfg = cfg; p.mu.Unlock() }

func waitProcessExit(done <-chan struct{}, timeout time.Duration) bool {
	if done == nil { return true }
	select {
	case <-done: return true
	case <-time.After(timeout): return false
	}
}

func terminateProcess(cmd *exec.Cmd, done <-chan struct{}) {
	if cmd == nil || cmd.Process == nil { return }
	_ = cmd.Process.Signal(syscall.SIGTERM)
	if waitProcessExit(done, 2*time.Second) { return }
	_ = cmd.Process.Kill()
	_ = waitProcessExit(done, time.Second)
}

func (p *SmartDNSProcess) Start() error {
	p.mu.Lock()
	if p.cmd != nil { p.mu.Unlock(); return nil }
	cmd := exec.Command(p.cfg.SmartDNSBin, "-f", "-x", "-c", p.cfg.SmartDNSConf)
	cmd.Stdout = os.Stdout; cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil { p.mu.Unlock(); return err }
	p.cmd = cmd
	done := make(chan struct{})
	p.done = done
	p.mu.Unlock()

	go func() {
		_ = cmd.Wait()
		close(done)
		p.mu.Lock()
		if p.cmd == cmd { p.cmd = nil; p.done = nil }
		p.mu.Unlock()
	}()

	// SmartDNS configuration errors normally make the child exit immediately.
	// Do not report a successful daemon start in that case.
	select {
	case <-done:
		p.mu.Lock(); if p.cmd == cmd { p.cmd = nil; p.done = nil }; p.mu.Unlock()
		return fmt.Errorf("smartdns exited during startup: %s", cmd.ProcessState.String())
	case <-time.After(500 * time.Millisecond):
	}
	return nil
}

func (p *SmartDNSProcess) Restart() error {
	p.mu.Lock(); old, done := p.cmd, p.done; p.cmd = nil; p.done = nil; p.mu.Unlock()
	terminateProcess(old, done)
	return p.Start()
}

func (p *SmartDNSProcess) Stop() {
	p.mu.Lock(); old, done := p.cmd, p.done; p.cmd = nil; p.done = nil; p.mu.Unlock()
	terminateProcess(old, done)
}

func DNSQueryOK() bool { return exec.Command("getent", "ahostsv4", "github.com").Run() == nil }

func ReadFirstNameserver(path string) string {
	f, e := os.Open(path); if e != nil { return "" }
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		fs := strings.Fields(sc.Text())
		if len(fs) >= 2 && fs[0] == "nameserver" { return fs[1] }
	}
	return ""
}
